### ISSUE TITLE
Tracking indentation

### ISSUE THREAD

**Issue by balajirama** [balajirama/Text-Parser#65]
- [x] Add attribute `track_indentation` which will enable tracking of indentation depth

- [x] Add attribute `indentation_str` with default char ` `.

- [x] Count the number of the indentation string at the beginning of a line.

- [x] Provide an L-value function `this_indent` to get the indentation level on a given line. Default return value is `undef` if `track_indentation` is false, or when called outside rules run during `read` operation.

- [x] Add tests

- [x] Bring coverage to 100%
